[package]
name = "dumb-wgpu-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.12.1", features = ["derive"] }
wgpu = "0.13.1"
winit = "0.27.3"
pollster = "0.2.5"
